### ISSUE TITLE
tar does not follow symlinks sometimes being used in user's document folder

### ISSUE THREAD

**Issue by nobruinfo** [MoDuLah/TDU2-SaveGame-Manager#1]
TDU2-SaveGame-Manager  uses `tar` to backup and restore game folder backups. Upon restore a command is used to unpack into the documents folder where the game keeps its savegame folder. It is currently used as a shell call which, if symlinks are present, ends in an uncaught error message:
```cmd
C:\Users\Superuser>C:\Windows\System32\tar.exe -xf "D:\aaaaaaaa\savegame_backup_2024.09.08_17.16.tar" -C "C:\Users\Superuser\OneDrive\Dokumente\Eden Games\Test Drive Unlimited 2\savegame"
./: Cannot extract through symlink \\\\?\\C:\\Users\\Superuser\\OneDrive\\Dokumente
./Alexander/: Cannot extract through symlink \\\\?\\C:\\Users\\Superuser\\OneDrive\\Dokumente
./congestionTV/: Cannot extract through symlink \\\\?\\C:\\Users\\Superuser\\OneDrive\\Dokumente
...
```
...and so on. This happens no matter where you're going to backup your files to. The error results in the tool remaining unresponsive. It seems Github is no longer allowing videos to directly play in browsers, so here a download:
https://github.com/user-attachments/assets/f130bf09-1769-46c9-a8a7-53f8d285b78f
A solution could be to toss `tar` entirely and use a Nuget library instead:
![grafik](https://github.com/user-attachments/assets/bf2e9ece-ba29-48e7-8576-8d69d8e50384)
Of course this is completely up to you. Thank you for the great tool this already is!

**Comment by MoDuLah** [comment]
Here's a response that incorporates the information and solutions discussed:

---

Hi nobruinfo,

Thank you for bringing this issue to our attention. We encountered similar problems with the tar utility when dealing with symlinks, as you described. To address this, we've transitioned to using the SharpZipLib library for handling backup and restore operations, which offers more robust support for file operations and avoids the symlink issues encountered with tar.

Here’s a brief overview of the updated approach:

1. **Switch to SharpZipLib**: Instead of using `tar.exe` for backup and restore, we now use SharpZipLib, a NuGet library that provides comprehensive support for file archiving and extraction. This change helps us bypass the symlink extraction issues and ensures a smoother backup and restore process.

2. **Updated Restore Method**: The restore functionality has been adapted to use SharpZipLib’s `TarArchive` class. This change resolves issues related to symlinks and ensures compatibility with various file paths. Below is an example of how we handle the extraction:

    ```csharp
    using (FileStream fs = new FileStream(backupFile, FileMode.Open, FileAccess.Read))
    using (TarArchive tarArchive = TarArchive.CreateInputTarArchive(fs))
    {
        tarArchive.ExtractContents(restoreDir);
    }
    ```

3. **Error Handling and User Feedback**: We've also improved error handling and user feedback during the restore process. For instance, the application now provides clearer messages if there are issues with permissions or directory paths, and it supports a better user experience.

4. **Testing and Validation**: We’re testing the new implementation thoroughly to ensure it works seamlessly across different environments and file structures.

You can check the updated code and details in the latest commits on our GitHub repository. If you encounter any further issues or have additional suggestions, please let us know!

Best regards,
MoDuLah
